class Translations:
    def __init__(self):
        self.data = {
            "ru": {
                "start_blocked": "Доступ заблокирован. Попробуйте позже.",
                "enter_password": "Введите пароль:",
                "wrong_password": "Неверный пароль. Осталось попыток: {left}",
                "blocked_24h": "Превышено число попыток. Блокировка на 24 часа.",
                "choose_language": "Выберите язык:",
                "lang_ru": "🇷🇺 Русский",
                "lang_en": "🇬🇧 English",
                "main_menu": "Вы в главном меню",
                "btn_language": "🌐 Язык",
                "btn_notifications": "🔔 Уведомления",
                "btn_templates": "🗂 Шаблоны",
                "btn_settings": "⚙️ Настройки",
                "btn_stats": "📊 Статистика",
                "btn_plugins": "🧩 Плагины",
                "notifications_title": "Настройки уведомлений",
                "notify_auth_on": "Уведомления об авторизации: Вкл",
                "notify_auth_off": "Уведомления об авторизации: Выкл",
                "notify_bump_on": "Уведомления о бампе лота: Вкл",
                "notify_bump_off": "Уведомления о бампе лота: Выкл",
                "notify_chat_on": "Уведомления о чатах: Вкл",
                "notify_chat_off": "Уведомления о чатах: Выкл",
                "notify_orders_on": "Уведомления о новых заказах: Вкл",
                "notify_orders_off": "Уведомления о новых заказах: Выкл",
                "btn_toggle_auth": "🔐 Перекл. авторизацию",
                "btn_toggle_bump": "📈 Перекл. бамп",
                "btn_back": "⬅️ Назад",
                "btn_turn_auth_on": "🔔 Включить Авторизацию",
                "btn_turn_auth_off": "🔕 Выключить Авторизацию",
                "btn_turn_bump_on": "📈 Включить Бамп",
                "btn_turn_bump_off": "🚫 Выключить Бамп",
                "btn_turn_chat_on": "📩 Включить Чат",
                "btn_turn_chat_off": "🙈 Выключить Чат",
                "btn_turn_orders_on": "🛒 Включить заказы",
                "btn_turn_orders_off": "🛒 Выключить заказы",
                "settings_title": "⚙️ Настройки",
                "btn_change_password": "🔑 Изменить пароль",
                "btn_change_session": "🔁 Изменить SESSION",
                "password_prompt": "Введите новый пароль:",
                "password_changed": "Пароль обновлен",
                "session_prompt": "Отправьте новый SESSION_COOKIE одним сообщением.",
                "session_changed": "SESSION_COOKIE обновлён",
                "session_change_failed": "Не удалось обновить SESSION: {error}",
                "btn_cancel": "❌ Отмена",
                "btn_send_message": "✉️ Отправить сообщение",
                "chat_notification": "📩 Новое сообщение от {username}:\n<code>{text}</code>",
                "reply_prompt": "Введите текст сообщения для отправки на Starvell. Чтобы отменить, нажмите «Отмена».",
                "reply_sent": "✅ Сообщение отправлено",
                "reply_failed": "⚠️ Не удалось отправить сообщение: {error}",
                "reply_cancelled": "ℹ️ Отправка отменена",
                "security_auth_blocked": "🚫 Попытка входа заблокирована\nID: <code>{id}</code>\nНик: <code>{username}</code>",
                "security_auth_success": "✅ Успешная авторизация\nID: <code>{id}</code>\nНик: <code>{username}</code>",
                "auth_success": "✅ Авторизация успешна\nID: <code>{id}</code>\nНик: <code>{username}</code>\nБаланс: <code>{balance}</code>\nЗаморожено: <code>{holded}</code>\nРейтинг: <code>{rating}</code>",
                "bot_version_line": "Версия бота: <code>{version}</code>",
                "auth_fail": "❌ Авторизация неуспешна",
                "bump_success": "📈 Бамп успешен: {title}",
                "bump_fail": "⚠️ Бамп не выполнен: {title}",
                "btn_open_link": "🔗 Открыть",
                "btn_profile": "👤 Профиль",
                "btn_author": "👤 Автор",
                "btn_channel": "📢 Канал",
                "btn_chat": "💬 Чат",
                "btn_order_open": "🔗 Открыть заказ",
                "btn_order_refund": "↩️ Вернуть средства",
                "btn_yes": "✅ Да",
                "btn_no": "❌ Нет",
                "btn_templates_add": "➕ Добавить шаблон",
                "btn_templates_delete": "🗑 Удалить шаблон",
                "btn_templates_list": "📄 Список шаблонов",
                "btn_templates_open": "🗂 Шаблоны",
                "btn_prev_page": "⬅️ Пред",
                "btn_next_page": "➡️ След",
                "order_new": "🛒 Новый заказ\nID: <code>{order_id}</code>\nПокупатель: <code>{buyer}</code>\nИгра: <code>{game}</code>\nКатегория: <code>{category}</code>\nКол-во: <code>{quantity}</code>\nЦена: <code>{total_price} ₽</code>",
                "order_completed": "✅ Заказ завершён\nID: <code>{order_id}</code>\nПокупатель: <code>{buyer}</code>\nИгра: <code>{game}</code>\nКатегория: <code>{category}</code>\nКол-во: <code>{quantity}</code>\nСумма: <code>{total_price} ₽</code>",
                "order_refund_prompt": "Вернуть средства по заказу <code>{order_id}</code>?",
                "order_refund_success": "✅ Возврат выполнен",
                "order_refund_cancelled": "ℹ️ Возврат отменён",
                "order_refund_failed": "⚠️ Не удалось выполнить возврат: {error}",
                "templates_title": "🗂 Шаблоны",
                "templates_intro": "Выберите действие:",
                "templates_empty": "Пока нет ни одного шаблона.",
                "templates_list_total": "Всего шаблонов: {count}",
                "templates_add_prompt": "Отправьте текст шаблона одним сообщением.",
                "templates_add_success": "Шаблон сохранён.",
                "templates_delete_choose": "Выберите шаблон для удаления:",
                "templates_delete_success": "Шаблон удалён.",
                "templates_delete_not_found": "Шаблон не найден или уже удалён.",
                "templates_reply_title": "Выберите шаблон для ответа:",
                "templates_reply_empty": "Нет сохранённых шаблонов. Добавьте их через /start.",
                "templates_cancelled": "Выбор шаблонов отменён.",
                "templates_page": "Страница {current} из {total}.",
                "stats_title": "📊 Статистика продаж",
                "stats_period_day": "За 24 часа",
                "stats_period_week": "За 7 дней",
                "stats_period_all": "За всё время",
                "stats_line": "✅ Завершено: {completed} | ↩️ Возвраты: {refund} | 🛒 Создано: {created}",
                "stats_sums_line": "💰 Суммы — ✅ {sum_completed} ₽ | ↩️ {sum_refund} ₽ | 🛒 {sum_created} ₽",
                "stats_line_with_sums": "✅ Завершено: <code>{completed}</code> (<code>{sum_completed}</code>) | ↩️ Возвраты: <code>{refund}</code> (<code>{sum_refund}</code>) | 🛒 Создано: <code>{created}</code> (<code>{sum_created}</code>)",
                "stats_summary_net": "За всё время заработано: <code>{net} ₽</code>",
                "stats_summary_waiting": "В ожидании: <code>{waiting} ₽</code>",
                "plugins_title": "🧩 Плагины",
                "plugins_wip": "Пока в разработке\nХотите заказать плагин для бота?",
                "btn_order_plugin": "💡 Заказать плагин",
            },
            "en": {
                "start_blocked": "Access is blocked. Try later.",
                "enter_password": "Enter password:",
                "wrong_password": "Wrong password. Attempts left: {left}",
                "blocked_24h": "Too many attempts. Blocked for 24 hours.",
                "choose_language": "Choose language:",
                "lang_ru": "🇷🇺 Русский",
                "lang_en": "🇬🇧 English",
                "main_menu": "You are in the main menu",
                "btn_language": "🌐 Language",
                "btn_notifications": "🔔 Notifications",
                "btn_templates": "🗂 Templates",
                "btn_settings": "⚙️ Settings",
                "btn_stats": "📊 Statistics",
                "btn_plugins": "🧩 Plugins",
                "notifications_title": "Notification settings",
                "notify_auth_on": "Auth notifications: On",
                "notify_auth_off": "Auth notifications: Off",
                "notify_bump_on": "Lot bump notifications: On",
                "notify_bump_off": "Lot bump notifications: Off",
                "notify_chat_on": "Chat notifications: On",
                "notify_chat_off": "Chat notifications: Off",
                "notify_orders_on": "New order notifications: On",
                "notify_orders_off": "New order notifications: Off",
                "btn_toggle_auth": "🔐 Toggle auth",
                "btn_toggle_bump": "📈 Toggle bump",
                "btn_back": "⬅️ Back",
                "btn_turn_auth_on": "🔔 Turn ON Authorization",
                "btn_turn_auth_off": "🔕 Turn OFF Authorization",
                "btn_turn_bump_on": "📈 Turn ON Bump",
                "btn_turn_bump_off": "🚫 Turn OFF Bump",
                "btn_turn_chat_on": "📩 Turn ON Chat",
                "btn_turn_chat_off": "🙈 Turn OFF Chat",
                "btn_turn_orders_on": "🛒 Turn ON Orders",
                "btn_turn_orders_off": "🛒 Turn OFF Orders",
                "settings_title": "⚙️ Settings",
                "btn_change_password": "🔑 Change password",
                "btn_change_session": "🔁 Change SESSION",
                "password_prompt": "Enter new password:",
                "password_changed": "Password updated",
                "session_prompt": "Send new SESSION_COOKIE in a single message.",
                "session_changed": "SESSION_COOKIE updated",
                "session_change_failed": "Failed to update SESSION: {error}",
                "btn_cancel": "❌ Cancel",
                "btn_send_message": "✉️ Send message",
                "chat_notification": "📩 New message from {username}:\n<code>{text}</code>",
                "reply_prompt": "Enter the message text to send to Starvell. Press “Cancel” to abort.",
                "reply_sent": "✅ Message sent",
                "reply_failed": "⚠️ Failed to send message: {error}",
                "reply_cancelled": "ℹ️ Sending cancelled",
                "security_auth_blocked": "🚫 Login attempt blocked\nID: <code>{id}</code>\nUsername: <code>{username}</code>",
                "security_auth_success": "✅ Successful authorization\nID: <code>{id}</code>\nUsername: <code>{username}</code>",
                "auth_success": "✅ Authorization successful\nID: <code>{id}</code>\nUsername: <code>{username}</code>\nBalance: <code>{balance}</code>\nHeld: <code>{holded}</code>\nRating: <code>{rating}</code>",
                "bot_version_line": "Bot version: <code>{version}</code>",
                "auth_fail": "❌ Authorization failed",
                "bump_success": "📈 Bump successful: {title}",
                "bump_fail": "⚠️ Bump failed: {title}",
                "btn_open_link": "🔗 Open",
                "btn_profile": "👤 Profile",
                "btn_author": "👤 Author",
                "btn_channel": "📢 Channel",
                "btn_chat": "💬 Chat",
                "btn_order_open": "🔗 Open order",
                "btn_order_refund": "↩️ Refund",
                "btn_yes": "✅ Yes",
                "btn_no": "❌ No",
                "btn_templates_add": "➕ Add template",
                "btn_templates_delete": "🗑 Delete template",
                "btn_templates_list": "📄 Templates list",
                "btn_templates_open": "🗂 Templates",
                "btn_prev_page": "⬅️ Prev",
                "btn_next_page": "➡️ Next",
                "order_new": "🛒 New order\nID: <code>{order_id}</code>\nBuyer: <code>{buyer}</code>\nGame: <code>{game}</code>\nCategory: <code>{category}</code>\nQty: <code>{quantity}</code>\nTotal: <code>{total_price} ₽</code>",
                "order_completed": "✅ Order completed\nID: <code>{order_id}</code>\nBuyer: <code>{buyer}</code>\nGame: <code>{game}</code>\nCategory: <code>{category}</code>\nQty: <code>{quantity}</code>\nTotal: <code>{total_price} ₽</code>",
                "order_refund_prompt": "Refund order <code>{order_id}</code>?",
                "order_refund_success": "✅ Refund completed",
                "order_refund_cancelled": "ℹ️ Refund cancelled",
                "order_refund_failed": "⚠️ Refund failed: {error}",
                "templates_title": "🗂 Templates",
                "templates_intro": "Choose an action:",
                "templates_empty": "No templates yet.",
                "templates_list_total": "Total templates: {count}",
                "templates_add_prompt": "Send the template text in a single message.",
                "templates_add_success": "Template saved.",
                "templates_delete_choose": "Choose a template to delete:",
                "templates_delete_success": "Template removed.",
                "templates_delete_not_found": "Template not found or already deleted.",
                "templates_reply_title": "Choose a template to send:",
                "templates_reply_empty": "No templates stored. Add them via /start.",
                "templates_cancelled": "Template selection cancelled.",
                "templates_page": "Page {current} of {total}.",
                "stats_title": "📊 Sales statistics",
                "stats_period_day": "Last 24 hours",
                "stats_period_week": "Last 7 days",
                "stats_period_all": "All time",
                "stats_line": "✅ Completed: {completed} | ↩️ Refunds: {refund} | 🛒 Created: {created}",
                "stats_sums_line": "💰 Totals — ✅ {sum_completed} ₽ | ↩️ {sum_refund} ₽ | 🛒 {sum_created} ₽",
                "stats_line_with_sums": "✅ Completed: <code>{completed}</code> (<code>{sum_completed}</code>) | ↩️ Refunds: <code>{refund}</code> (<code>{sum_refund}</code>) | 🛒 Created: <code>{created}</code> (<code>{sum_created}</code>)",
                "stats_summary_net": "All-time earned: <code>{net} ₽</code>",
                "stats_summary_waiting": "Pending: <code>{waiting} ₽</code>",
                "plugins_title": "🧩 Plugins",
                "plugins_wip": "Work in progress\nWant to order a plugin for the bot?",
                "btn_order_plugin": "💡 Order a plugin",
            },
        }

    def t(self, lang: str, key: str, **kwargs) -> str:
        base = self.data.get(lang) or self.data.get("ru")
        value = base.get(key, key)
        return value.format(**kwargs)


